import Head from 'next/head'
import Image from 'next/image'
import ToastApp from '../components/toast'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastApp />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Sentinal Safety</a>
        </h1>

        <p className={styles.description}>
          Get started by
          <code className={styles.code}>Login/Signup</code>
        </p>

        <div className={styles.grid}>
          <a href="/alerts" className={styles.card}>
            <h2>Alert History &rarr;</h2>
            <p>Find in-depth information about previous alerts.</p>
          </a>

          <a href="/userDetails" className={styles.card}>
            <h2>Manage Account  &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="/dashboard"
            className={styles.card}
          >
            <h2>Dashboard &rarr;</h2>
            <p>Discover the insights aand events caused..</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>something more &rarr;</h2>
            <p>

            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          Sentinal
        </a>
      </footer>
    </div>
  )
}
